---
- hosts: all
  tasks:
          - ini_file:
                  path: /etc/systemd/system.conf
                  section: Manager
                  option: RuntimeWatchdogSec
                  value: 20
                  no_extra_spaces: yes

          - ini_file:
                  path: /etc/systemd/system.conf
                  section: Manager
                  option: ShutdownWatchdogSec
                  value: 200
                  no_extra_spaces: yes

