---
- hosts: all
  tasks:
          - ini_file:
                  path: /etc/systemd/logind.conf
                  section: Login
                  option: HandleSuspendKey
                  value: ignore
                  no_extra_spaces: yes

          - ini_file:
                  path: /etc/systemd/logind.conf
                  section: Login
                  option: HandleHibernateKey
                  value: ignore
                  no_extra_spaces: yes

          - ini_file:
                  path: /etc/systemd/logind.conf
                  section: Login
                  option: HandleLidSwitch
                  value: ignore
                  no_extra_spaces: yes

          - ini_file:
                  path: /etc/systemd/logind.conf
                  section: Login
                  option: HandleLidSwitchDocked
                  value: ignore
                  no_extra_spaces: yes

          - systemd:
                  name: systemd-logind.service
                  state: restarted
