- name: Stop ambitorio-ipfs docker containers
  command: ./stop.sh
  args:
    chdir: /home/ambitorio/iwe_ipfs_docker/docker
  listen: Start IPFS docker

- name: Start ambitorio-ipfs docker containers
  command: ./start.sh ansible
  args:
    chdir: /home/ambitorio/iwe_ipfs_docker/docker
  listen: Start IPFS docker
