- name: Install docker packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
  tags:
    - docker

- name: Enable docker service
  systemd:
    name: docker.service
    enabled: yes
  tags:
    - docker
