- name: Install docker packages
  dnf:
    name: ['docker', 'docker-compose']
    state: present
  tags:
    - docker

- name: Enable docker service
  systemd:
    name: docker.service
    enabled: yes
  tags:
    - docker
