- name: Check current plymouth theme
  shell: cat /etc/plymouth/plymouthd.conf | grep -q "^Theme=details"
  register: plymouth
  changed_when: plymouth.rc != 0
  failed_when: false
  notify:
    - Set plymouth theme to details
  tags:
    - services
    - plymouth
